language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=soundid setup.py test
  - make test-sdist

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
